# Generated by Django 3.0.4 on 2020-03-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helpline_Portal', '0004_auto_20200325_1928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
