# Generated by Django 3.0 on 2021-04-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question_Answer', '0001_initial'),
        ('Helpline_Portal', '0006_auto_20210329_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.ManyToManyField(to='Question_Answer.Category'),
        ),
    ]
