# Generated by Django 3.0 on 2021-04-11 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helpline_Portal', '0007_profile_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='course',
            new_name='courses',
        ),
    ]
