# Generated by Django 3.0.4 on 2020-03-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helpline_Portal', '0008_auto_20200331_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
