# Generated by Django 3.0 on 2021-04-12 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helpline_Portal', '0008_auto_20210411_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='courses',
            new_name='course',
        ),
    ]
