# Generated by Django 3.0.4 on 2020-04-02 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Helpline_Portal', '0009_delete_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='users',
            name='password2',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
