# Generated by Django 3.0.5 on 2020-04-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helpline_Portal', '0010_auto_20200402_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('regnumber', models.CharField(max_length=11, primary_key=True, serialize=False)),
            ],
        ),
    ]
