# Generated by Django 3.0.5 on 2020-05-10 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Helpline_Portal', '0012_auto_20200510_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='level',
        ),
        migrations.AddField(
            model_name='profile',
            name='regnumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
    ]
