# Generated by Django 3.0.5 on 2020-05-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helpline_Portal', '0015_auto_20200510_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='regnumber',
        ),
    ]
