# Generated by Django 3.0.5 on 2020-05-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helpline_Portal', '0020_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpg', null=True, upload_to=''),
        ),
    ]
