# Generated by Django 3.0.5 on 2020-05-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helpline_Portal', '0021_auto_20200520_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='user_avatar.jpg', null=True, upload_to=''),
        ),
    ]
