# Generated by Django 3.0 on 2021-04-13 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Question_Answer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lecturer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
