# Generated by Django 3.0.5 on 2020-04-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question_Answer', '0002_auto_20200420_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Answer_text',
            new_name='answer_text',
        ),
    ]
