# Generated by Django 3.0 on 2021-04-19 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Question_Answer', '0002_category_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='category',
            name='lecturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
